language: csharp
sudo: required

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - dotnet --version
  - dotnet restore
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then dotnet test tests/Tests/Tests.csproj; fi'

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    dotnet: 2.1
    mono: none
