
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: JD6RZJ00/a4C5TBIzQSE6SHQun3o04wdgSyz4+uu6QFGtoWFcQuqag21+IUzY95f
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
before_build:
  - dotnet --version
  - where dotnet
  - dotnet restore
  - nuget install coveralls.io -version 1.3.4 -OutputDirectory .\packages
build: off
build_script:
  - dotnet pack src/Mandrill.net --include-symbols --configuration Release --output artifacts
test: off
test_script:
  - if defined MANDRILL_API_KEY dotnet test tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - if defined MANDRILL_API_KEY .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover .\tests\coverage.xml
artifacts:
  - path: 'src\**\*.nupkg'
deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: znBJ3DWOhYRo43eFKnVGodpP2p7fw1Lpdqf27D2SJ61FJemoGQHiAGgZBEmwjVLE
  skip_symbols: false
  artifact: /.*\.nupkg/
